Bootstrap: localimage
From: ../output/python3.6.img

%labels
  Features numpy, pandas, matplotlib, python 3.6, Theano 1.0.3, gcc7, openblas

%help
  Theano 1.0.3 Running on python 3.6

%post
  apt-get update
  apt-get install -y libopenblas-dev

  conda install six tornado pillow
  conda install numpy pandas matplotlib
  conda install -c conda-forge theano
  conda install -c conda-forge/label/gcc7 theano
  conda install -c conda-forge/label/broken theano
