Bootstrap: localimage
From: ../output/python3.7.img

%labels
  Features numpy, pandas, matplot, scikit, scipy, seaborn, statsmodels, bokeh

%help
  Python 3.7 with all data science packages

%post
  apt-get update

  conda install six, tornado, pillow
  conda install numpy, pandas, matplotlib, scipy, scikit-learn
  conda install seaborn, statsmodels, bokeh
