Bootstrap: localimage
From: ../output/python3.6.img

%labels
  Features python3.6, six, tornado, pillow, numpy, pandas, matplot, scikit-learn and image, scipy, seaborn, statsmodels, bokeh

%help
  Python 3.6 with all data science packages

%post
  apt-get update

  conda install six tornado pillow
  conda install numpy pandas matplotlib scipy
  conda install scikit-learn scikit-image
  conda install seaborn statsmodels bokeh
