Bootstrap: localimage
From: ../output/tf1.10-py3.6.img

%labels
  Features  keras-gpu 2.2.4 on tensorflow 1.10, python 3.6

%help
  Keras 2.2.4 gpu with Tensorflow 1.10 backend on Python 2.7

%post
  apt-get update
  conda install -c anaconda keras-gpu
