Bootstrap: localimage
From: ../output/python3.6.img

%labels
  Features numpy, pandas, matplotlib, tensorflow-gpu, python 3.6, tensorboard, openblas

%help
  Tensorflow 1.10 gpu running on python 3.6

%post
  apt-get update
  apt-get install -y libopenblas-dev

  conda install six tornado pillow
  conda install numpy pandas matplotlib
  conda install -c anaconda tensorflow-gpu tensorflow-tensorboard
