Bootstrap: localimage
From: ../output/tensorflow.img

%labels
  Features tensflow, keras

%help
  Keras 2.2.4 with tf backend

%post
  apt-get update
  conda install -c anaconda keras-gpu 
