Bootstrap: docker
From: ubuntu:16.04

%labels
  Features base-image, vim, git, wget, curl, ....

%help
  This is the base image for all cluster images

%post
  apt-get update
  apt-get install -y vim
  apt-get install -y git
  apt-get install -y wget
  apt-get install -y htop
  apt-get install -y curl
