Bootstrap: localimage
From: ../output/python3.6.img

%labels
  Features numpy, pandas, matplot, tensorflow

%help
  Pytorch 1.0 Running on python 3.6 and cuda 9.0

%post
  apt-get update

  conda install numpy pandas matplotlib
  conda install pytorch torchvision -c pytorch
