Bootstrap: localimage
From: ../output/base_ubuntu_1804.img

%labels
  Features gcc 6, g++ 6, buildessentials, cmake, autoconf, automake, boost, libtools

%help
  gcc 6 tools

%post
  apt-get update
  apt-get install -y gcc-6
  apt-get install -y g++-6
  apt-get install -y libtool
  apt-get install -y make
  apt-get install -y gdb
  apt-get install -y autoconf
  apt-get install -y automake
  apt-get install -y autotools-dev
  apt-get install -y cmake
  apt-get install -y linux-headers-generic
  apt-get install -y linux-libc-dev
  apt-get install -y libgc-dev
  apt-get install -y libboost-all-dev
