Bootstrap: localimage
From: ../output/python2.7.img

%labels
  Features numpy, pandas, matplot, tensorflow-gpu, python 2.7, tensorboard, openblas

%help
  Tensorflow 1.10 gpu running on python 2.7

%post
  apt-get update
  apt-get install -y libopenblas-dev

  conda install six tornado pillow
  conda install numpy pandas matplotlib
  conda install -c anaconda tensorflow-gpu tensorflow-tensorboard 
